# Generated by Django 4.0.3 on 2022-05-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image_company',
            field=models.CharField(default='SII', max_length=1024),
        ),
    ]
