# Generated by Django 4.0.3 on 2022-03-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nukura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nukurastore',
            name='author_name',
            field=models.CharField(default='Murat', max_length=255),
        ),
    ]
