# Generated by Django 4.0.3 on 2022-05-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nukura', '0002_nukurastore_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstorerelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ok'), (2, 'Fine'), (3, 'Good'), (4, 'Amazing'), (5, 'Incredible')], null=True),
        ),
    ]
