# Generated by Django 4.0.3 on 2022-04-02 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nukura', '0003_nukurastore_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStoreRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('in_storemarks', models.BooleanField(default=False)),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'OK'), (2, 'FINE'), (3, 'GOOD'), (4, 'AMAZING'), (5, 'INCREDIBLE')])),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nukura.nukurastore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
