# Generated by Django 4.0.3 on 2022-05-13 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_company'),
        ('nukura', '0003_alter_userstorerelation_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='nukurastore',
            name='description',
            field=models.TextField(default='Its cool'),
        ),
        migrations.AlterField(
            model_name='nukurastore',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_books', to='users.company'),
        ),
    ]
