# Generated by Django 4.0.3 on 2022-04-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nukura', '0005_nukurastore_readers_alter_nukurastore_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='nukurastore',
            name='image',
            field=models.ImageField(default='image/burger-2.jpg', upload_to=''),
        ),
    ]
