# Generated by Django 4.0.3 on 2022-04-23 12:05

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0002_rename_text_reviews_message_reviews_sent_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reviews',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
