# Generated by Django 4.0.3 on 2022-04-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0003_alter_reviews_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reviews',
            managers=[
            ],
        ),
    ]
